name: trends-of-ai-semester-project
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  # Add additional packages here, make sure to include the correct version numbers!
  - python=3.12.0
  - pytorch==2.5.1
  - numpy==1.26.4
  - matplotlib==3.8.4
  - ipython==8.28.0
  - ipykernel==6.29.5
  - pandas==2.2.3
  - scikit-learn==1.5.2
  - jupyterlab==4.3.0
  - seaborn==0.13.2
  - datasets==3.0.2
  - transformers==4.46.2
  - torchtext==0.6.0
  - nltk==3.9.1
  - gymnasium==1.0.0
  - pygame==2.6.1 
  - tensorboard==2.18.0
  - tensorboardx==2.6.2.2
  - pip:
    - tensorflow==2.18.0